application:
  redis:
    host: 127.0.0.1
    port: 6379
    password: ok
    cache-name: buckets

  account-types:
    - name: LOUSY
      duration: 1d
      messages-per-duration: 1

    - name: MEDIOCRE
      duration: 1s
      messages-per-duration: 2

    - name: BRONZE
      duration: 1s
      messages-per-duration: 5

    - name: SILVER
      duration: 1s
      messages-per-duration: 10

    - name: GOLD
      duration: 1s
      messages-per-duration: 20

    - name: PLATINUM
      duration: 1s
      messages-per-duration: 50

  account-configs:
    - short-number: 20000
      type: LOUSY

    - short-number: 21111
      type: MEDIOCRE

    - short-number: 22222
      type: MEDIOCRE

    - short-number: 23333
      type: BRONZE

    - short-number: 24444
      type: SILVER

    - short-number: 25555
      type: GOLD

    - short-number: 26666
      type: PLATINUM
